#!/bin/sh

# Get YADM Local Class
MACHINE_CLASS=$(yadm config local.class)

if [ "$MACHINE_CLASS" = "Work" ]
then

  #Source Secrets
  if [ -f "${HOME}/.secrets" ]; then 
    # shellcheck source=/dev/null
    . "${HOME}/.secrets"
  else
    echo "Secrets not found. Cannot continue."
    exit 1
  fi 

  # Maven Token
  MAVEN_ARTIFACTORY_TOKEN_FILE=${HOME}/.maven_artifactory_token
  ART_MAVEN_TOKEN_GEN_URL=https://token-generator.artifactory.homedepot.com/api/maven/generateToken
  
  TOKEN_GOOD=0
  # Check if the token exists
  if [ ! -f "${MAVEN_ARTIFACTORY_TOKEN_FILE}" ]; then
    TOKEN_GOOD=1
  else
    ART_MAVEN_TOKEN=$(cat "${MAVEN_ARTIFACTORY_TOKEN_FILE}")
    CURRENT_UNIX_TIMESTAMP=$(date +%s)
    ART_MAVEN_JWT_EXP_TIMESTAMP="$(jwt decode "${ART_MAVEN_TOKEN}" -j | jq -r .payload.exp)"
    if [ $? -ne 0 ] || [ "${ART_MAVEN_JWT_EXP_TIMESTAMP}" -lt "${CURRENT_UNIX_TIMESTAMP}" ]; then
      TOKEN_GOOD=1
    fi
  fi 

  if [ ${TOKEN_GOOD} -eq 1 ]; then
    ART_MAVEN_TOKEN=$(curl -s --request POST "${ART_MAVEN_TOKEN_GEN_URL}" --data-urlencode "username=${LDAP_USER}" --data-urlencode "password=${LDAP_PASS}" | jq -r .access_token)
    echo "${ART_MAVEN_TOKEN}" > "${MAVEN_ARTIFACTORY_TOKEN_FILE}"
  fi

  
  # Docker Token
  DOCKER_ARTIFACTORY_TOKEN_FILE=${HOME}/.docker_artifactory_token
  ART_DOCKER_TOKEN_GEN_URL=https://token-generator.artifactory.homedepot.com/api/docker/generateToken

  TOKEN_GOOD=0
  # Check if the token exists
  if [ ! -f "${DOCKER_ARTIFACTORY_TOKEN_FILE}" ]; then
    TOKEN_GOOD=1
  else
    ART_DOCKER_TOKEN=$(cat "${DOCKER_ARTIFACTORY_TOKEN_FILE}")
    CURRENT_UNIX_TIMESTAMP=$(date +%s)
    ART_DOCKER_JWT_EXP_TIMESTAMP="$(jwt decode "${ART_DOCKER_TOKEN}" -j | jq .payload.exp)"
    if [ $? -ne 0 ] || [ "${ART_DOCKER_JWT_EXP_TIMESTAMP}" -lt "${CURRENT_UNIX_TIMESTAMP}" ]; then
      TOKEN_GOOD=1
    fi
  fi 

  if [ ${TOKEN_GOOD} -eq 1 ]; then
    ART_DOCKER_TOKEN=$(curl -s --request POST "${ART_DOCKER_TOKEN_GEN_URL}" --data-urlencode "username=${LDAP_USER}" --data-urlencode "password=${LDAP_PASS}" | jq -r .access_token)
    echo "${ART_DOCKER_TOKEN}" > "${DOCKER_ARTIFACTORY_TOKEN_FILE}"
  fi

  export ART_LOGIN_USR=${LDAP_USER}
  export ART_LOGIN_PSW=${LDAP_PASS}
  export ART_TOKEN=${ART_MAVEN_TOKEN}
  export ART_MAVEN_TOKEN=${ART_MAVEN_TOKEN}
  export ARTIFACTORY_TOKEN=${ART_MAVEN_TOKEN}
  export ART_DOCKER_TOKEN=${ART_DOCKER_TOKEN}
fi
