#!/bin/sh

if [ -d "$HOME/workspace" ]
then
  PROJECTS_DIRECTORY=$HOME/workspace
elif  [ -d "$HOME/workspaces" ]
then
  PROJECTS_DIRECTORY=$HOME/workspaces
fi

PROJECTS_DIRECTORY_DEPTH=2


project() {
      fuzzy_find=$(find -L "$PROJECTS_DIRECTORY" -maxdepth $PROJECTS_DIRECTORY_DEPTH -type d | fzf -1 -q "$1")
      cd "$fuzzy_find" || exit
}
alias p="project"