#!/bin/sh

if command -v gcloud > /dev/null 2>&1
then
    export GCLOUD_PATH=$HOME/google-cloud-sdk
    export CLOUDSDK_PYTHON=$(which python3)

    source "${GCLOUD_PATH}/path.zsh.inc"
    source "${GCLOUD_PATH}/completion.zsh.inc"
fi