#!/bin/sh

# Get YADM Local Class
MACHINE_CLASS=$(yadm config local.class)

if [ "$MACHINE_CLASS" = "Work" ]
then
    export GOPATH=$HOME/go
    export GOROOT=/usr/local/opt/go/libexec
    export PATH=$PATH:$GOPATH/bin
    export PATH=$PATH:$GOROOT/bin

    export GOPRIVATE=github.homedepot.com
fi

