#!/bin/sh

export PATH="/usr/local/bin:$PATH"

# if [ -d "/usr/local/opt/libpq/bin" ]
# then
#   export PATH="/usr/local/opt/libpq/bin:$PATH"
# fi

if [ -d "/opt/homebrew/Cellar/openssl@3/3.1.0/bin" ]
then
  export PATH="/opt/homebrew/Cellar/openssl@3/3.1.0/bin:$PATH"
fi

if [ -d "$HOME/.cargo/bin" ]
then
  export PATH="$HOME/.cargo/bin:$PATH"
fi

